pipeline {

    agent any

    tools {
        maven 'Maven'
    }

    options {
        skipDefaultCheckout(true)
    }

    environment {
        IMAGE_NAME = 'billing-software'
        CONTAINER_NAME = 'billing-container'
    }

    stages {

        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    credentialsId: 'Git-Credentials',
                    url: 'https://github.com/Srinath2679/Billing-Software.git'
            }
        }

        stage('Build Jar') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }

        stage('Copy Dockerfile') {
            steps {
                sh 'cp Dockerfile .'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME .'
            }
        }

        stage('Deploy Container') {
            steps {
                sh '''
                    docker stop $CONTAINER_NAME || true
                    docker rm $CONTAINER_NAME || true

                    docker run -d \
                    --name $CONTAINER_NAME \
                    -p 8081:8080 \
                    $IMAGE_NAME
                '''
            }
        }
    }
}