pipeline {

    agent any

    tools {
        maven 'Maven'
    }

    options {
        skipDefaultCheckout(true)
    }

    environment {
        APP_REPO = 'https://github.com/Srinath2679/Billing-Software.git'
        IMAGE_NAME = 'billing-software'
        CONTAINER_NAME = 'billing-container'
    }

    stages {

        stage('Checkout DevOps Repo') {
            steps {
                checkout scm
            }
        }

        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout App Code') {
            steps {
                dir('app') {
                    git branch: 'main',
                        credentialsId: 'Git-Credentials',
                        url: "${APP_REPO}"
                }
            }
        }

        stage('Build Jar') {
            steps {
                dir('app') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Prepare Docker Context') {
            steps {
                sh 'ls -la app'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('app') {
                    sh 'docker build -t $IMAGE_NAME .'
                }
            }
        }

        stage('Deploy Container') {
            steps {
                sh '''
                    docker stop $CONTAINER_NAME || true
                    docker rm $CONTAINER_NAME || true

                    docker run -d \
                    --name $CONTAINER_NAME \
                    -p 8081:8080 \
                    $IMAGE_NAME
                '''
            }
        }
    }
}